# Generated by Django 5.0.7 on 2024-09-12 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('total_rooms', models.IntegerField()),
                ('address', models.TextField(max_length=100)),
                ('phone_number', models.TextField(max_length=11)),
            ],
        ),
    ]
