# Generated by Django 5.1 on 2024-09-14 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_bookingmanage_client_room_alter_hotel_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='tip',
        ),
        migrations.RemoveField(
            model_name='bookingmanage',
            name='client',
        ),
        migrations.DeleteModel(
            name='Hotel',
        ),
        migrations.AddField(
            model_name='bookingmanage',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_client', to='hotel.client'),
        ),
    ]
