# Generated by Django 5.1 on 2024-09-20 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_remove_bill_tip_remove_bookingmanage_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmanage',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_staff', to='hotel.staff'),
        ),
        migrations.AddField(
            model_name='client',
            name='client_phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='staff_id_number',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='staff_phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.IntegerField(null=True),
        ),
    ]
