# Generated by Django 5.1 on 2024-09-23 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_alter_room_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_status',
            field=models.CharField(choices=[('NOT READY', 'NOT READY'), ('READY', 'READY')], default='NOT READY', max_length=50),
        ),
    ]
