# Generated by Django 5.0.7 on 2024-09-30 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_rename_name_staff_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'AVAILABLE'), ('NON-AVAI', 'NON-AVAI')], default='NON-AVAI', max_length=50),
        ),
    ]
