# Generated by Django 5.1 on 2024-10-04 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0010_alter_room_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='status',
        ),
    ]
