# Generated by Django 5.1 on 2024-10-06 05:53

import hotel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0011_remove_staff_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='cccd_pic',
            field=models.FileField(blank=True, null=True, upload_to=hotel.models.client_pic_upload),
        ),
        migrations.AddField(
            model_name='staff',
            name='staff_pic',
            field=models.FileField(blank=True, null=True, upload_to=hotel.models.staff_pic_upload),
        ),
    ]
