# Generated by Django 5.1 on 2024-10-11 11:15

import hotel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0013_bill_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cccd_pic',
            field=models.ImageField(blank=True, null=True, upload_to=hotel.models.client_pic_upload),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_pic',
            field=models.ImageField(blank=True, null=True, upload_to=hotel.models.staff_pic_upload),
        ),
    ]
