# Generated by Django 5.1 on 2024-10-12 04:28

import hotel.models
import hotel.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0015_alter_client_cccd_pic_alter_staff_staff_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cccd_pic',
            field=models.ImageField(blank=True, null=True, upload_to=hotel.models.client_pic_upload, validators=[hotel.validator.validate_cccd_pic_size, hotel.validator.validate_image_file_extension]),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_pic',
            field=models.ImageField(blank=True, null=True, upload_to=hotel.models.staff_pic_upload, validators=[hotel.validator.validate_staff_pic_size, hotel.validator.validate_image_file_extension]),
        ),
    ]
